### PR TITLE
SQLAlchemy 1.4 support

### PR DESCRIPTION
**Pull request by dwreeves**
Fixes issue #50.

### CODE REVIEW

**Comment by dgipps** [comment]
Anything I can do to help get this merged? This is currently blocking us from upgrading to SQLAlchemy 1.4.

**Comment by dwreeves** [comment]
@dgipps Aside from tagging @jeancochrane and praying, I'm not sure what else to do. 😬

**Comment by jeancochrane** [comment]
Thanks for this @dwreeves @dgipps ! I appreciate the mention, my repo notifications are kind of a mess right now. This seems reasonable to me but it looks like something is up with our pytest configuration. If you want to try to figure it out you're welcome to, otherwise I'll try to dig in later this week.

**Comment by dwreeves** [comment]
OK my previous commit was extremely lazy. I dug into it a bit more and found out that there is a lot of reliance on deprecated things:

`contextual_connect` is totally removed in 1.4, so I deleted it. The `_engine` fixture mocking `connect` is sufficient.

The tests failing to even start is due to [this](https://github.com/ClearcodeHQ/pytest-postgresql/blob/e74f0cd8462305118052ce48a3aa37f2dbb6b86e/CHANGES.rst#backward-incompatibilities):

> ### Backward Incompatibilities
> * Removed init_postgresql_database and drop_postgresql_database functions. They were long deprecated and their role perfectly covered by DatabaseJanitor class.

So swapping to that works.

---

[Here is my run of this workflow](https://github.com/dwreeves/pytest-flask-sqlalchemy/actions/runs/1054560638), everything passes.

Can you approve this workflow? https://github.com/jeancochrane/pytest-flask-sqlalchemy/actions/runs/1054560707

Thanks @jeancochrane!

**Comment by jeancochrane** [comment]
Thanks for digging in here @dwreeves, this looks great to me 🙏🏻 @dgipps Can you use changes from the main branch for now? I'd like to do a little more testing before cutting a release, but I'm going to aim for next week.

**Comment by dwreeves** [comment]
Thanks for review, and thank you for creating and maintaining this project @jeancochrane. This package has been extremely useful for me; glad to contribute to it.

**Comment by bbtdev** [comment]
can we update the documentation as well?
` NameError: name 'init_postgresql_database' is not defined`

**Comment by jeancochrane** [comment]
Thanks for the flag @bbtdev, will update this weekend 👍🏻

**Pull request merged**
